  [build]
  builder = "nixpacks"

  [deploy]
  preDeployCommand = "python manage.py migrate"
  startCommand = "python manage.py collectstatic --noinput && gunicorn agro_fastservice.wsgi --log-file - --bind 0.0.0.0:$PORT"
  healthcheckPath = "/"