# Generated by Django 6.0.5 on 2026-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=6)),
                ('categoria', models.CharField(max_length=200)),
                ('imagen', models.CharField(default='default.png', max_length=200)),
            ],
        ),
    ]
