# Generated by Django 6.0.5 on 2026-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('direccion_finca', models.CharField(max_length=200)),
                ('m2_finca', models.PositiveIntegerField(blank=True, null=True)),
                ('kg_estimados', models.PositiveIntegerField(blank=True, null=True)),
                ('otros_datos', models.TextField(blank=True, default='')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
