# Generated by Django 6.0.5 on 2026-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='direccion_finca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
