# Generated by Django 6.0.5 on 2026-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mensajecontacto_direccion_finca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField()),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
