# Generated by Django 6.0.5 on 2026-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='servicio',
            field=models.CharField(blank=True, choices=[('torillo', 'Torillo'), ('colla', 'Colla'), ('torillo_colla', 'Torillo + Colla')], default='', max_length=20),
        ),
    ]
